/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LabRouteImport } from './routes/lab'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ArcadeRouteImport } from './routes/arcade'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiEnrollRouteImport } from './routes/api/enroll'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcadeRoute = ArcadeRouteImport.update({
  id: '/arcade',
  path: '/arcade',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnrollRoute = ApiEnrollRouteImport.update({
  id: '/api/enroll',
  path: '/api/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arcade': typeof ArcadeRoute
  '/dashboard': typeof DashboardRoute
  '/lab': typeof LabRoute
  '/profile': typeof ProfileRoute
  '/roadmap': typeof RoadmapRoute
  '/api/chat': typeof ApiChatRoute
  '/api/enroll': typeof ApiEnrollRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arcade': typeof ArcadeRoute
  '/dashboard': typeof DashboardRoute
  '/lab': typeof LabRoute
  '/profile': typeof ProfileRoute
  '/roadmap': typeof RoadmapRoute
  '/api/chat': typeof ApiChatRoute
  '/api/enroll': typeof ApiEnrollRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arcade': typeof ArcadeRoute
  '/dashboard': typeof DashboardRoute
  '/lab': typeof LabRoute
  '/profile': typeof ProfileRoute
  '/roadmap': typeof RoadmapRoute
  '/api/chat': typeof ApiChatRoute
  '/api/enroll': typeof ApiEnrollRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arcade'
    | '/dashboard'
    | '/lab'
    | '/profile'
    | '/roadmap'
    | '/api/chat'
    | '/api/enroll'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arcade'
    | '/dashboard'
    | '/lab'
    | '/profile'
    | '/roadmap'
    | '/api/chat'
    | '/api/enroll'
  id:
    | '__root__'
    | '/'
    | '/arcade'
    | '/dashboard'
    | '/lab'
    | '/profile'
    | '/roadmap'
    | '/api/chat'
    | '/api/enroll'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArcadeRoute: typeof ArcadeRoute
  DashboardRoute: typeof DashboardRoute
  LabRoute: typeof LabRoute
  ProfileRoute: typeof ProfileRoute
  RoadmapRoute: typeof RoadmapRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiEnrollRoute: typeof ApiEnrollRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcade': {
      id: '/arcade'
      path: '/arcade'
      fullPath: '/arcade'
      preLoaderRoute: typeof ArcadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/enroll': {
      id: '/api/enroll'
      path: '/api/enroll'
      fullPath: '/api/enroll'
      preLoaderRoute: typeof ApiEnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArcadeRoute: ArcadeRoute,
  DashboardRoute: DashboardRoute,
  LabRoute: LabRoute,
  ProfileRoute: ProfileRoute,
  RoadmapRoute: RoadmapRoute,
  ApiChatRoute: ApiChatRoute,
  ApiEnrollRoute: ApiEnrollRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
